.TH ZEBU 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed; see man(7), man(1)
.SH NAME
zebu \- ZFS-based network filesystem backup tool
.SH SYNOPSIS
.B zebu
.I [options]
.SH "DESCRIPTION"
Create backups, including backups of remote machines, using ZFS snapshots.
.PP
.BR zebu
takes a configured list of ZFS file systems and performs regular backup
tasks.  This can include copying data from a remote server to the local
file system using
.BR rsync
, and generally includes making snapshots, deleting old snapshots, and
may someday include transporting incremental snapshots to a remote machine
for off-site archival.
.PP
Backups take place in a series of phases, described below.
.BR zebu
iterates over each ZFS file system, and runs through all applicable phases
in turn (rather than running one phase at a time across each file system).
.PP
More documentation about
.BR zebu
will be forthcoming.  Someday.
.SH PHASES
.SS Snapshotting
ZFS snapshots are created, using the configured prefix with the current time
stamp appended as a snapshot name.  Time stamps are of the form
.I <year><month><day><hour><minute><second>
and are listed numerically (e.g., snap-20080607204837).
.PP
A file system with a defined
.I rsync_server
(see \fBzebu.conf(5)\fP for details) will be assumed to contain a copy of
files on a remote system.
.BR zebu
will use
.BR rsync
to copy files into the ZFS file system.  Files will be copied into the
.I tree
subdirectory.  Additionally, three log files will be created:
\fIexcludes\fP, which contains a list of exclude patterns used during the
\fBrsync\fP, \fIrsync_log\fP, which contains the log of the \fBrsync\fP
process itself, and \fIzebu_log\fP, which lists applicable messages from
.BR zebu
during the transfer.  Once the rsync process is completed successfully,
and all log files created, the ZFS file system receives a snapshot.  If the
.BR rsync
did not complete successfully, no snapshot is created.
.PP
Following any
.BR rsync
transfers, all ZFS file systems are treated identically through the remaining
.BR zebu
phases.
.SS Cleanup
Any snapshot older than indicated in the
\fItime_to_live\fP configuration file parameter is deleted.  Age is determined
by comparing the current time with the time portion of a snapshot name.
.PP
.BR Zebu
only concerns itself with snapshots whose names begin with the
.I snap_prefix
configuration parameter.  All other snapshots are ignored.
.PP
.BR Zebu
will never attempt to delete snapshots if only one snapshot is remaining.
This is intended to preserve at least one good snapshot, to avoid potentially
removing the last remaining viable backup (particularly important for
\fBrsync\fR-based backup file systems).
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-no-cleanup\fR
Skip the cleanup phase, and continue to the next phase.
.TP
\fB\-f\fR, \fB\-\-file\fR \fIconfig-file\fR
Use
.I config-file
as a configuration file.
.TP
\fB\-F\fR, \fB\-\-filesystem\fR \fIfilesystem\fR
Only operate on the named ZFS file system.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a summary of options and commands, then exit.
.TP
\fB\-s\fR, \fB\-\-no-snapshot\fR
Skip the snapshot phase, and continue to the next phase.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be a bit more verbose, and provide status messages during a run.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SH SEE ALSO
.nf
zebu.conf(5)
.SH AUTHOR
\fBzebu\fR was written by Mike Shuey <shuey@fmepnet.org> and is licensed under
the terms of the GNU Public License, version 2 or higher.
.SH "KNOWN ISSUES"
.B zebu
does not assist in making offsite backups of any managed ZFS file systems.
