.TH ZEBU.CONF 5
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed; see man(7), man(1)
.SH NAME
zebu.conf \- configuration file for zebu
.SH "DESCRIPTION"
The zebu.conf config file provides information about ZFS filesystems for
zebu to manage.  By default,
.BR zebu
will look in
.I /usr/local/etc/zebu/zebu.conf
followed by
.I /etc/zebu/zebu.conf
for a config file, and use the first file found.
.PP
The file format is rather simple, and follows a layout common to many other
programs' config files.  Lines beginning with a hash (#) are assumed to be
comments.  The file itself is divided into sections, with each section
containing zero or more
.BR key=value
pairs.
.PP
Section names should be on lines by themselves, surrounded by square brackets
(\fB[]\fR).  Each section name is assumed to be a ZFS file system
.BR zebu
should manipulate.  The name
.BR DEFAULT
has special meaning; values defined in the
.BR DEFAULT
section are taken as defaults for all other sections.  These values can
be overridden on a section-by-section basis.
.PP
In a \fBvalue\fR portion of a \fBkey=value\fR pair, the string
.BR %(dir)s
will be replaced by the current section name.  This is useful for inserting
the file system name into a default option.
.SH "AVAILABLE KEYS"
.BR zebu
will use the following keys to adjust its behavior:
.\"
.TP
\fBadditional_excludes\fR
Path to a file containing additional \fBrsync\fR excludes.  The contents of
this file are appended to the configured \fBexcludes\fR file (if any), and
passed to the
.BR rsync
command during an \fBrsync\fR-based backup.

In general, this option will be used to add server-specific excludes (on top
of the default excludes) during an
.BR rsync
backup.

This is silently ignored for normal ZFS file systems.
.\"
.TP
\fBbasepath\fR
This is the base path for the remote end of \fBrsync\fR-based backups.

\fBbasepath\fR is only valid for \fBrsync\fR backup file systems, and is
silently ignored for conventional ZFS file systems.
.\"
.TP
\fBdoCleanup\fR
This boolean indicates whether zebu should bother running the cleanup
(snapshot-deleting) phase on a particular vault.  If False, the cleanup
phase is skipped; if True, cleanup is performed.  This is also valid in the
.I DEFAULT
section.

The default value is True.
.TP
\fBdoSnapshot\fR
This boolean indicates whether zebu should perform the snapshot creation
phase on a particular vault.  If True, snapshots are performed; if False,
snapshots will not be made.  This is also valid in the
.I DEFAULT
section.

The default value is True.
.TP
.TP
\fBdoTransmit\fR
This boolean indicates whether zebu should attempt to transmit snapshots
from the indicated vault.  If True, snapshots are transmitted; if False,
this step is skipped.  This is also valid in the
.I DEFAULT
section.

The default value is False.
\fBexcludes\fR
Path to a file containing \fBrsync\fR excludes.  This contents of this file
are passed to the
.BR rsync
command during an \fBrsync\fR-based backup.

In general, this option will be used to provide the default excludes in the
.I DEFAULT
section.

This is silently ignored for normal ZFS file systems.
.\"
.TP
\fBexpiretime\fR
\fBzebu\fR's "cleanup" phase will delete old ZFS snapshots.  Snapshots are
considered old if they are have aged more than \fIexpiretime\fR.

.BR zebu
will never attempt to delete snapshots if only one snapshot is remaining.

\fBexpiretime\fR is expressed as a :-separated time - 
.I <days>:<hours>:<minutes>:<seconds>
.\"
.TP
\fBsnap_prefix\fR
ZFS snapshots will be created with names beginning with \fBsnap_prefix\fR.
This defaults to "zebu-".
.\"
.TP
\fBrecurse\fR
If set to \fIyes\fR (or \fItrue\fR, or \fI1\fR), \fBzebu\fR will create
and delete snapshots recursively on a given ZFS file system.  This option is
silently ignored for an \fBrsync\fR-based backup file system (mainly because
it doesn't make sense in that context).
.\"
.TP
\fBrsync_path\fR
Path to the \fBrsync\fR command on the local system.  Only valid for
\fBrsync\fR-based backup file systems.

Defaults to \fIrsync\fR (so the current PATH will be searched).
.\"
.TP
\fBrsync_server\fR
The remote server to use for \fBrsync\fR-based backups.  If an
\fBrsync_server\fR is specified, the file system is assumed to contain a
copy of another machine.  If no \fBrsync_server\fR is specified, the file
system is assumed to be a normal ZFS file system.
.\"
.TP
\fBtransmit_cmd\fR
This is a shell command that should transmit and store your ZFS snapshots.  The output
of \fBzfs send\fR will be piped into this shell command, so ideally it should be something
that will send \fBstdin\fR to a remote server and either archive it or play it back on
another ZFS pool.
.TP
\fBzfs_path\fR
Path to the 
.BR zfs
executable.  Defaults to \fI/usr/bin/zfs\fR.
.SH SEE ALSO
.nf
zebu(1)
.SH AUTHOR
\fBzebu\fR was written by Mike Shuey <shuey@fmepnet.org> and is licensed under
the terms of the GNU Public License, version 2 or higher.
