.TH ZEBU 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed; see man(7), man(1)
.SH NAME
zebu \- ZFS-based network filesystem backup tool
.SH SYNOPSIS
.B zebu
.I [global options] <file> <command> [command arguments]
.SH "DESCRIPTION"
Create a backup image of a client directory tree, and keep old backups as
ZFS snapshots.
.PP
More documentation about
.BR zebu
will be forthcoming.  Someday.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a summary of options and commands, then exit.
.TP
\fB\-f\fR, \fB\-\-file\fR \fIconfig-file\fI
Use
.I config-file
as a configuration file.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be a bit more verbose, and provide status messages during a run.
.TP
\fB\-s\fR, \fB\-\-no-snapshot\fR
Skip the snapshot phase, and continue to the next phase.
.SH CONFIGURATION FILE
More on this later.
.SS subsection
more here
.SH "KNOWN ISSUES"
The documentation for
.B zebu
is woefully incomplete.
.SH AUTHOR
\fBzebu\fR was written by Mike Shuey <shuey@fmepnet.org> and is licensed under
the terms of the GNU Public License, version 2 or higher.
